# Generated by Django 3.1.14 on 2023-11-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=5)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
    ]
